### ISSUE TITLE
Optimize by Removing fetch-depth: 0 to Reduce Fetch Time

### ISSUE THREAD

**Issue by hocyadav** [Rebilly/lexi#320]
- The current configuration uses `fetch-depth: 0`, which fetches the entire history and takes more time. Can we try removing this to see if it works without fetching the entire history?

Here is the updated YAML configuration without `fetch-depth: 0`:

```yaml
name: Report readability

# This action only works on pull request events
on: pull_request

jobs:
    report-readability:
        name: Report readability
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - uses: Rebilly/lexi@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  glob: '**/*.md'
```

Removing `fetch-depth: 0` will fetch only the latest commit by default, which should be faster.
