### ISSUE TITLE
push example

### ISSUE THREAD

**Issue by shane0** [Rebilly/lexi#61]
made a push example if anyone wants that

later I'll try the same on a gitlab or azure pipeline

```yml
name: lexi

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm i
        npm i tsx -g
        yarn run:local:report ./test-data/old ./test-data/new
```
